### ISSUE TITLE
Fix logo font

### ISSUE THREAD

**Issue by andreas-wilm** [nf-core/vipr#11]
Installed Maven Pro manually and Inkscape via Homebrew (on a Mac). Font is not applied, but no error is printed.

**Comment by ewels** [comment]
Maybe this can be an issue on the nf-core/logo repo - to throw an error?

For this problem though, perhaps @MaxUlysse can help, he wrote the script.

**Comment by MaxUlysse** [comment]
There might be an issue in the font name between Mac and Linux.
Something like `MavenPro` vs `Maven Pro`
But if you have Inkscape you should be able to change the font to the proper one on the newly generated svg file.

I definitively need to have a look at Python libraries to generate SVG and PNG images, to make it more reproducible and reliable.

**Comment by MaxUlysse** [comment]
I suggest one simple fix for now, I'll update the logo, and then we'll sort this issue out later.
How does that sound @andreas-wilm ?
