### ISSUE TITLE
params.tracedir in nextflow.config

### ISSUE THREAD

**Issue by Ritzttk** [nf-core/vipr#29]
When I run the pipeline, I found the error : 
`${params.tracedir} is not found ` 
I don't find any record which has related to tracedir. So I added the value of tracedir like outdir

```nextflow
params {
    // defaults. best not changed
    version = '1.0-dev' // Pipeline version
    container = "nfcore/vipr:${version}" // for GIS translated into conda env name!
    nf_required_version = '0.30.2' // Minimum version of nextflow required
    outdir = 'results'
    tracedir = 'results'
    // Pipeline options
    skip_kraken = false
}
```
It worked but is it wrong ?.

Thanks,
Kien

**Comment by Ritzttk** [comment]
@ewels Thanks for updating. I am using this pipeline for our unit. I start to set up. Hope that I am not bothering you too much
Kiên

**Comment by ewels** [comment]
No, not at all! It's great to have you on board and using the nf-core pipelines! It's also nice to have an excuse to drive development on projects 😉

**Comment by ewels** [comment]
Hi @Ritzttk,

This should hopefully be resolved now. Please try pulling the latest version of the code and try again. Let's see what the next bug is! 😉 

Phil
